name = "simple-temp-mail"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
DOMAIN = "gyf123.dpdns.org"


[[d1_databases]]
binding = "DB"
database_name = "temp-email-db"
# 【必填】你的 D1 数据库 ID
database_id = "ca916e37-4600-43ed-b606-e7437861cb58"
